package quant.entity;
// Generated 2018-5-7 14:39:14 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AssemblyHedgeOrder generated by hbm2java
 */
@Entity
@Table(name = "ASSEMBLY_HEDGE_ORDER", catalog = "quant")
public class AssemblyHedgeOrder implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String dataId;
	private String hedgeId;
	private String plantfrom;
	private String currency;
	private String orderId;
	private String orderSide;
	private String orderStatus;
	private BigDecimal orderPrice;
	private BigDecimal orderQuantity;
	private BigDecimal transPrice;
	private String createTimestamp;
	private String modifyTimestamp;

	public AssemblyHedgeOrder() {
	}

	public AssemblyHedgeOrder(String dataId) {
		this.dataId = dataId;
	}

	public AssemblyHedgeOrder(String dataId, String hedgeId, String plantfrom, String currency, String orderId,
			String orderSide, String orderStatus, BigDecimal orderPrice, BigDecimal orderQuantity,
			BigDecimal transPrice, String createTimestamp, String modifyTimestamp) {
		this.dataId = dataId;
		this.hedgeId = hedgeId;
		this.plantfrom = plantfrom;
		this.currency = currency;
		this.orderId = orderId;
		this.orderSide = orderSide;
		this.orderStatus = orderStatus;
		this.orderPrice = orderPrice;
		this.orderQuantity = orderQuantity;
		this.transPrice = transPrice;
		this.createTimestamp = createTimestamp;
		this.modifyTimestamp = modifyTimestamp;
	}

	@Id
	@GenericGenerator(name="uuid", strategy="uuid")
	@GeneratedValue(generator="uuid")
	@Column(name = "DATA_ID", unique = true, nullable = false, length = 32)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "HEDGE_ID", length = 32)
	public String getHedgeId() {
		return this.hedgeId;
	}

	public void setHedgeId(String hedgeId) {
		this.hedgeId = hedgeId;
	}

	@Column(name = "PLANTFROM", length = 30)
	public String getPlantfrom() {
		return this.plantfrom;
	}

	public void setPlantfrom(String plantfrom) {
		this.plantfrom = plantfrom;
	}

	@Column(name = "CURRENCY", length = 15)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "ORDER_ID", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "ORDER_SIDE", length = 20)
	public String getOrderSide() {
		return this.orderSide;
	}

	public void setOrderSide(String orderSide) {
		this.orderSide = orderSide;
	}

	@Column(name = "ORDER_STATUS", length = 15)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_PRICE", precision = 20, scale = 10)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "ORDER_QUANTITY", precision = 20, scale = 10)
	public BigDecimal getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(BigDecimal orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "TRANS_PRICE", precision = 20, scale = 10)
	public BigDecimal getTransPrice() {
		return this.transPrice;
	}

	public void setTransPrice(BigDecimal transPrice) {
		this.transPrice = transPrice;
	}

	@Column(name = "CREATE_TIMESTAMP", length = 13)
	public String getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(String createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Column(name = "MODIFY_TIMESTAMP", length = 13)
	public String getModifyTimestamp() {
		return this.modifyTimestamp;
	}

	public void setModifyTimestamp(String modifyTimestamp) {
		this.modifyTimestamp = modifyTimestamp;
	}

}
