package quant.entity;
// default package
// Generated 2018-6-4 11:50:17 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AssemblyHedgeOrder generated by hbm2java
 */
@Entity
@Table(name = "CANDIDATE_ASSEMBLY_HEDGE_ORDER", catalog = "quant")
public class CandidateAssemblyHedgeOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dataId;
	private String hedgeId;
	private String plantform;
	private String currencyPair;
	private String quoteCurrency;
	private String baseCurrency;
	private String orderId;
	private String orderSide;
	private String orderStatus;
	private BigDecimal orderPrice;
	private BigDecimal orderQuantity;
	private BigDecimal transPrice;
	private BigDecimal feeRate;
	private String createTimestamp;
	private String modifyTimestamp;

	public CandidateAssemblyHedgeOrder() {
	}

	public CandidateAssemblyHedgeOrder(String dataId) {
		this.dataId = dataId;
	}

	public CandidateAssemblyHedgeOrder(String dataId, String hedgeId, String plantform, String currencyPair,
			String quoteCurrency, String baseCurrency, String orderId, String orderSide, String orderStatus,
			BigDecimal orderPrice, BigDecimal orderQuantity, BigDecimal transPrice, BigDecimal feeRate,
			String createTimestamp, String modifyTimestamp) {
		this.dataId = dataId;
		this.hedgeId = hedgeId;
		this.plantform = plantform;
		this.currencyPair = currencyPair;
		this.quoteCurrency = quoteCurrency;
		this.baseCurrency = baseCurrency;
		this.orderId = orderId;
		this.orderSide = orderSide;
		this.orderStatus = orderStatus;
		this.orderPrice = orderPrice;
		this.orderQuantity = orderQuantity;
		this.transPrice = transPrice;
		this.feeRate = feeRate;
		this.createTimestamp = createTimestamp;
		this.modifyTimestamp = modifyTimestamp;
	}

	@Id
	@GenericGenerator(name="uuid", strategy="uuid")
	@GeneratedValue(generator="uuid")
	@Column(name = "DATA_ID", unique = true, nullable = false, length = 32)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "HEDGE_ID", length = 32)
	public String getHedgeId() {
		return this.hedgeId;
	}

	public void setHedgeId(String hedgeId) {
		this.hedgeId = hedgeId;
	}

	@Column(name = "PLANTFORM", length = 30)
	public String getPlantform() {
		return this.plantform;
	}

	public void setPlantform(String plantform) {
		this.plantform = plantform;
	}

	@Column(name = "CURRENCY_PAIR", length = 20)
	public String getCurrencyPair() {
		return this.currencyPair;
	}

	public void setCurrencyPair(String currencyPair) {
		this.currencyPair = currencyPair;
	}

	@Column(name = "QUOTE_CURRENCY", length = 10)
	public String getQuoteCurrency() {
		return this.quoteCurrency;
	}

	public void setQuoteCurrency(String quoteCurrency) {
		this.quoteCurrency = quoteCurrency;
	}

	@Column(name = "BASE_CURRENCY", length = 10)
	public String getBaseCurrency() {
		return this.baseCurrency;
	}

	public void setBaseCurrency(String baseCurrency) {
		this.baseCurrency = baseCurrency;
	}

	@Column(name = "ORDER_ID", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "ORDER_SIDE", length = 20)
	public String getOrderSide() {
		return this.orderSide;
	}

	public void setOrderSide(String orderSide) {
		this.orderSide = orderSide;
	}

	@Column(name = "ORDER_STATUS", length = 15)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_PRICE", precision = 25, scale = 15)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "ORDER_QUANTITY", precision = 25, scale = 15)
	public BigDecimal getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(BigDecimal orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "TRANS_PRICE", precision = 25, scale = 15)
	public BigDecimal getTransPrice() {
		return this.transPrice;
	}

	public void setTransPrice(BigDecimal transPrice) {
		this.transPrice = transPrice;
	}

	@Column(name = "FEE_RATE", precision = 6, scale = 5)
	public BigDecimal getFeeRate() {
		return this.feeRate;
	}

	public void setFeeRate(BigDecimal feeRate) {
		this.feeRate = feeRate;
	}

	@Column(name = "CREATE_TIMESTAMP", length = 13)
	public String getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(String createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Column(name = "MODIFY_TIMESTAMP", length = 13)
	public String getModifyTimestamp() {
		return this.modifyTimestamp;
	}

	public void setModifyTimestamp(String modifyTimestamp) {
		this.modifyTimestamp = modifyTimestamp;
	}

}
