package quant.entity;
// Generated 2018-2-9 22:27:23 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * LiveOrderPairs generated by hbm2java
 */
@Entity
@Table(name = "LIVE_ORDER_PAIRS", schema = "dbo", catalog = "quant")
public class LiveOrderPairs implements java.io.Serializable {

	private String dataId;
	private String plantform;
	private String currency;
	private String buyOrderId;
	private BigDecimal buyOrderPrice;
	private BigDecimal buyOrderQuantity;
	private String buyOrderStatus;
	private Long createTimestamp;
	private Long modifyTimestamp;
	private String sellOrderId;
	private BigDecimal sellOrderPrice;
	private BigDecimal sellOrderQuantity;
	private String sellOrderStatus;

	public LiveOrderPairs() {
	}

	public LiveOrderPairs(String dataId) {
		this.dataId = dataId;
	}

	public LiveOrderPairs(String dataId, String plantform, String currency, String buyOrderId, BigDecimal buyOrderPrice,
			BigDecimal buyOrderQuantity, String buyOrderStatus, Long createTimestamp, Long modifyTimestamp,
			String sellOrderId, BigDecimal sellOrderPrice, BigDecimal sellOrderQuantity, String sellOrderStatus) {
		this.dataId = dataId;
		this.plantform = plantform;
		this.currency = currency;
		this.buyOrderId = buyOrderId;
		this.buyOrderPrice = buyOrderPrice;
		this.buyOrderQuantity = buyOrderQuantity;
		this.buyOrderStatus = buyOrderStatus;
		this.createTimestamp = createTimestamp;
		this.modifyTimestamp = modifyTimestamp;
		this.sellOrderId = sellOrderId;
		this.sellOrderPrice = sellOrderPrice;
		this.sellOrderQuantity = sellOrderQuantity;
		this.sellOrderStatus = sellOrderStatus;
	}

	@Id
	@GenericGenerator(name="generator", strategy="uuid")
	@GeneratedValue(generator="generator")
	@Column(name = "DATA_ID", unique = true, nullable = false, length = 32)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "PLANTFORM", length = 30)
	public String getPlantform() {
		return this.plantform;
	}

	public void setPlantform(String plantform) {
		this.plantform = plantform;
	}

	@Column(name = "CURRENCY", length = 15)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "BUY_ORDER_ID", length = 32)
	public String getBuyOrderId() {
		return this.buyOrderId;
	}

	public void setBuyOrderId(String buyOrderId) {
		this.buyOrderId = buyOrderId;
	}

	@Column(name = "BUY_ORDER_PRICE", precision = 20, scale = 10)
	public BigDecimal getBuyOrderPrice() {
		return this.buyOrderPrice;
	}

	public void setBuyOrderPrice(BigDecimal buyOrderPrice) {
		this.buyOrderPrice = buyOrderPrice;
	}

	@Column(name = "BUY_ORDER_QUANTITY", precision = 20, scale = 10)
	public BigDecimal getBuyOrderQuantity() {
		return this.buyOrderQuantity;
	}

	public void setBuyOrderQuantity(BigDecimal buyOrderQuantity) {
		this.buyOrderQuantity = buyOrderQuantity;
	}

	@Column(name = "BUY_ORDER_STATUS", length = 15)
	public String getBuyOrderStatus() {
		return this.buyOrderStatus;
	}

	public void setBuyOrderStatus(String buyOrderStatus) {
		this.buyOrderStatus = buyOrderStatus;
	}

	@Column(name = "CREATE_TIMESTAMP", precision = 10, scale = 0)
	public Long getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Long createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Column(name = "MODIFY_TIMESTAMP", precision = 10, scale = 0)
	public Long getModifyTimestamp() {
		return this.modifyTimestamp;
	}

	public void setModifyTimestamp(Long modifyTimestamp) {
		this.modifyTimestamp = modifyTimestamp;
	}

	@Column(name = "SELL_ORDER_ID", length = 32)
	public String getSellOrderId() {
		return this.sellOrderId;
	}

	public void setSellOrderId(String sellOrderId) {
		this.sellOrderId = sellOrderId;
	}

	@Column(name = "SELL_ORDER_PRICE", precision = 20, scale = 10)
	public BigDecimal getSellOrderPrice() {
		return this.sellOrderPrice;
	}

	public void setSellOrderPrice(BigDecimal sellOrderPrice) {
		this.sellOrderPrice = sellOrderPrice;
	}

	@Column(name = "SELL_ORDER_QUANTITY", precision = 20, scale = 10)
	public BigDecimal getSellOrderQuantity() {
		return this.sellOrderQuantity;
	}

	public void setSellOrderQuantity(BigDecimal sellOrderQuantity) {
		this.sellOrderQuantity = sellOrderQuantity;
	}

	@Column(name = "SELL_ORDER_STATUS", length = 15)
	public String getSellOrderStatus() {
		return this.sellOrderStatus;
	}

	public void setSellOrderStatus(String sellOrderStatus) {
		this.sellOrderStatus = sellOrderStatus;
	}

}
