package quant.entity;
// default package
// Generated 2018-6-9 12:15:54 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * LowPriceHedgeOrder generated by hbm2java
 */
@Entity
@Table(name = "LOW_PRICE_HEDGE_ORDER", catalog = "quant")
public class LowPriceHedgeOrder implements java.io.Serializable {

	private static final long serialVersionUID = -7756462185689807621L;
	private String dataId;
	private String hedgeId;
	private String exchangeName;
	private String currencyPair;
	private String orderSide;
	private BigDecimal orderPrice;
	private BigDecimal orderQuantity;
	private String orderStatus;
	private String orderId;
	private BigDecimal feeRate;
	private Long createTimestamp;
	private Long modifyTimestamp;

	public LowPriceHedgeOrder() {
	}

	public LowPriceHedgeOrder(String dataId) {
		this.dataId = dataId;
	}

	public LowPriceHedgeOrder(String dataId, String hedgeId, String exchangeName, String currencyPair, String orderSide,
			BigDecimal orderPrice, BigDecimal orderQuantity, String orderStatus, String orderId, BigDecimal feeRate,
			Long createTimestamp, Long modifyTimestamp) {
		this.dataId = dataId;
		this.hedgeId = hedgeId;
		this.exchangeName = exchangeName;
		this.currencyPair = currencyPair;
		this.orderSide = orderSide;
		this.orderPrice = orderPrice;
		this.orderQuantity = orderQuantity;
		this.orderStatus = orderStatus;
		this.orderId = orderId;
		this.feeRate = feeRate;
		this.createTimestamp = createTimestamp;
		this.modifyTimestamp = modifyTimestamp;
	}

	@Id
	@GenericGenerator(name="uuid", strategy="uuid")
	@GeneratedValue(generator="uuid")
	@Column(name = "DATA_ID", unique = true, nullable = false, length = 32)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "HEDGE_ID", length = 32)
	public String getHedgeId() {
		return this.hedgeId;
	}

	public void setHedgeId(String hedgeId) {
		this.hedgeId = hedgeId;
	}

	@Column(name = "EXCHANGE_NAME", length = 30)
	public String getExchangeName() {
		return this.exchangeName;
	}

	public void setExchangeName(String exchangeName) {
		this.exchangeName = exchangeName;
	}

	@Column(name = "CURRENCY_PAIR", length = 15)
	public String getCurrencyPair() {
		return this.currencyPair;
	}

	public void setCurrencyPair(String currencyPair) {
		this.currencyPair = currencyPair;
	}

	@Column(name = "ORDER_SIDE", length = 4)
	public String getOrderSide() {
		return this.orderSide;
	}

	public void setOrderSide(String orderSide) {
		this.orderSide = orderSide;
	}

	@Column(name = "ORDER_PRICE", precision = 25, scale = 15)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "ORDER_QUANTITY", precision = 25, scale = 15)
	public BigDecimal getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(BigDecimal orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "ORDER_STATUS", length = 15)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_ID", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "FEE_RATE", precision = 6, scale = 5)
	public BigDecimal getFeeRate() {
		return this.feeRate;
	}

	public void setFeeRate(BigDecimal feeRate) {
		this.feeRate = feeRate;
	}

	@Column(name = "CREATE_TIMESTAMP", precision = 13, scale = 0)
	public Long getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Long createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Column(name = "MODIFY_TIMESTAMP", precision = 13, scale = 0)
	public Long getModifyTimestamp() {
		return this.modifyTimestamp;
	}

	public void setModifyTimestamp(Long modifyTimestamp) {
		this.modifyTimestamp = modifyTimestamp;
	}

}
